### ISSUE TITLE
NeuroHub homepage updates

### ISSUE THREAD

**Issue by chrismaskell** [neurohub/neurohub#24]
- Change tag line underneath NH logo in the banner to “Bringing together data, computational infrastructure platforms and state-of-the-art technologies” (no oxford comma)
- [Replace NH circle graphic with new version](https://www.mcgill.ca/hbhl/files/hbhl/neurohub_circle_graphic_png_transparent-01.png )
- Change header text to “Collaborative, multidisciplinary and reproducible research” instead of “An open science infrastructure for reproducible, collaborative and multidisciplinary research”
- Remove “View more information on the NeuroHub vision”

- When platform launches Nov. 17/18, change button to “Register now”

**Comment by 3design** [comment]
Completed the following:

Change tag line underneath NH logo in the banner to “Bringing together data, computational infrastructure platforms and state-of-the-art technologies” (no oxford comma)

Replace NH circle graphic with new version

Change header text to “Collaborative, multidisciplinary and reproducible research” instead of “An open science infrastructure for reproducible, collaborative and multidisciplinary research”

Remove “View more information on the NeuroHub vision”

**Comment by chrismaskell** [comment]
Header text on this page should read (copy paste error): Collaborative, multidisciplinary and reproducible research
